### ISSUE TITLE
 Hey，我之前看到你在superuser上提过问题 后来这个解决了吗

### ISSUE THREAD

**Issue by mushroom11s** [tylerrrkd/Dasgras_Visualization#2]

**Comment by mushroom11s** [comment]
![image](https://user-images.githubusercontent.com/28756933/47762754-e6fadb00-dcf8-11e8-95f9-c928d8b20885.png)

**Comment by tylerrrkd** [comment]
@poppycokey 没有 哈哈哈哈 你怎么找到我的gayhub的？后来我直接重装系统了。你也误删了yum?

**Comment by mushroom11s** [comment]
你superuser资料上写得gayhub地址. 不是误删了,想着升级python3  犯傻把自带的python删了 删完就知道不对了 然后重装yum. 装了3次都是这个错  我后来没办法 从别的机器上copy了一份过去python 和 yum 就好了

**Comment by tylerrrkd** [comment]
@poppycokey 哇！！还有这种操作！！谢谢你！！！
